DEBUG: false
TESTING: false

dataSource: db # or csv

db:
  csv: /app/assets/titanic.csv
  file: /app/data/titanic.db
  table: titanic
  # percentiles.sql: ./assets/percentiles.sql

swagger: /app/assets/swagger.yaml

logger:
  name: Titanic
  level: INFO